#!/usr/bin/env bash
# Bash script that installs nginx web server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
echo "Hello World!" > /var/www/html/index.html
service nginx start
