#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Update the package list and install Nginx
apt-get -y update -y
apt-get -y install nginx -y

echo "Hello World!" > /var/www/html/index.html

# Create a new Nginx configuration file for the redirection
touch /etc/nginx/sites-available/redirect_me
cat <<EOF > /etc/nginx/sites-available/redirect_me
server {
	listen 80;

	server_name 100.25.141.117 tobydev.tech;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
EOF

# Link the configuration file to the sites-enabled directory
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

nginx -t
service nginx restart
