#!/usr/bin/env bash
# Install HAProxy
sudo apt-get update
sudo apt-get install haproxy -y

# Configure HAProxy to send traffic to web-01 and web-02 using a roundrobin algorithm
echo "
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    mode http
    server 170996-web-01 54.208.227.111:80 check
    server 170996-web-02 34.201.174.167:80 check
" >> /etc/haproxy/haproxy.cfg

# Enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
