#!/usr/bin/env bash
# Configuration of Nginx to run on port 80

# Removes the enabled default Nginx configuration file
sudo rm -rf /etc/nginx/sites-enabled/default

# Creates a symbolic link between your /etc/nginx/sites-available/default and /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Start/restart Nginx
sudo service nginx restart
